### ISSUE TITLE
小时天气预警显示unkown

### ISSUE THREAD

**Issue by Licolnlee** [c1pher-cn/heweather#23]
![image](https://github.com/user-attachments/assets/d7a68d50-de1a-4022-9cc3-83e8cdab169e)
![image](https://github.com/user-attachments/assets/0e532c03-04ca-4421-bc9b-10cae2422ba7)
![image](https://github.com/user-attachments/assets/6f1f56e7-e5c8-4d24-9aaf-3ba9ba8ec215)
我通过development tool先对services测试了是正常的，可以输出yaml格式的天气结果，然后通过yaml转json放到templates中测试也没问题，缩进也没问题，但是小时天气预警的sensor还是显示unkown，而且attribute也没有，不知道哪里有问题，感觉是无法获取到forecasts这个字典？

**Comment by Licolnlee** [comment]
已通过查阅官方论坛进行解决，下面附上新版本的代码。
```yaml
template:
  - trigger:
      - platform: time_pattern
        hours: "*"
    action:
      - service: weather.get_forecasts
        data:
          type: hourly
        target:
          entity_id: weather.he_feng_tian_qi
        response_variable: hourly
    sensor:
      - name: "小时天气预警"
        unique_id: weather_forecast_hourly
        state: >
          {% if hourly['weather.he_feng_tian_qi'].forecast[0].condition in ('sunny','cloudy','partlycloudy','windy') %}
            off
          {% else %}
            on
          {% endif %}
        attributes:
          states: >
            {% if hourly['weather.he_feng_tian_qi'].forecast[0].condition in ('sunny','cloudy','partlycloudy','windy') %}
              未来一小时，天气{{ hourly['weather.he_feng_tian_qi'].forecast[0].text }}，没有降雨
            {% else %}
              接下来一小时会有{{ hourly['weather.he_feng_tian_qi'].forecast[0].text }}，降水概率为 {{ hourly['weather.he_feng_tian_qi'].forecast[0].precipitation_probability }}%
            {% endif %}
```

对应的自动化代码

```yaml
automation:
  - alias: "小时天气预警"
    trigger:
      - platform: state
        entity_id: sensor.weather_forecast_hourly
        from: "Off"
        to: "On"
    action:
      - service: notify.events
        data:
          title: "小时天气预警"
          message: "小时天气预警!!! {{state_attr('sensor.weather_forecast_hourly','states') }} "  
    initial_state: true
  - alias: "自然灾害预警"
    trigger:
      - platform: state
        entity_id: sensor.zai_hai_yu_jing
        from: "Off"
        to: "On"
      - platform: state
        entity_id: binary_sensor.yuhang_warning
        from: "Off"
        to: "On"
    action:
      - service: notify.events
        data:
          title: "自然灾害预警"
          message: "自然灾害预警!!! {{state_attr('sensor.zai_hai_yu_jing','states') }} "
      - service: notify.events
        data:
          title: "自然灾害预警"
          message: "自然灾害预警提醒!!! {{state_attr('binary_sensor.yuhang_warning','states') }} "
    initial_state: true
```
